### ISSUE TITLE
Group project Kanban Board

### ISSUE THREAD

**Issue by tinatsina** [tinatsina/online-kitchen#22]
https://github.com/users/tinatsina/projects/2/views/1

**Comment by dasileker** [comment]
### **Hi @tinatsina,** 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## **Invalid Code Review Request**

You have submitted a project, that _**The issue is not having  names of the students and it doesn't have a valid link to the github/projects.**_

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by tinatsina** [comment]
OK thank you, I will create a new issue and fix the changes as shown
